### ISSUE TITLE
Build under Linux

### ISSUE THREAD

**Issue by tvjon** [ncassetta/Fl_MIDIKeyboard#1]
Hello Nicola.

You'll be pleased to know it works under Linux "Raspbian" on a "Raspberry Pi" computer board.

I'm about average with C. but know little of C++. Fortunately, only a few changes are necessary 
to your source code.

The linux FLTK headers have some files with mixed case, so 

#include <Fl/fl_ask.H>

#include <FL/fl_draw.H>

I just have 

#include <RtMidi.h>

instead of

#include "RtMidi-2.0.1/RtMidi.h"

Here's a screenshot.

I'm unsure what the layout should look like.

The vertical test app doesn't show any keyboard at all.

The only other app I use with fltk is Dillo browser, so maybe I can get a clue from looking through its source (which too 
builds ok in Raspbian)

ciao,

john
![fl-keybd](https://cloud.githubusercontent.com/assets/5360158/25138757/e55e5a64-244a-11e7-8b23-936f911da2a0.jpg)

**Comment by ncassetta** [comment]
Thanks for your feedback!

I forgot to correct an old bug related to FLTK 1.1.10 which I used to develop the widget (a method of the Fl_Scroll widget has a different meaning in 1.3.x).
I also added the screenshot of sample programs.

Now all should work, let me know if is OK
